[package]
name = "mirage"
version = "0.1.0"
authors = ["Nathan Stocks <nathan.stocks@gmail.com>"]
edition = "2018"

[dependencies]
image = "0.21.1"
num-complex = "0.2.1"
clap = "3.0.0-beta.1"
regex = "1"